# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evF3YMvkrWtJApLJeoNSCQ7z8bNdR2BC
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("train.csv")  # For CSV files
print(df.head())

print(df.isnull().sum())

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df.drop(columns=['Cabin'], inplace=True)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 5))
sns.histplot(df['Age'], bins=20, kde=True, color='blue')
plt.xlabel("Age")
plt.ylabel("Count")
plt.title("Age Distribution of Titanic Passengers")
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x='Sex', data=df, palette="coolwarm")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.title("Gender Distribution of Titanic Passengers")
plt.show()

"""Interpretation: You’ll see how many males and females were on board."""

sns.barplot(x='Sex', y='Survived', data=df)
plt.title("Survival Rate by Gender")
plt.ylabel("Survival Rate")
plt.show()

"""Interpretation: This will show whether men or women had a higher survival chance.

3.

**Patterns in Data**
"""

sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Survival by Age")
plt.show()

"""This helps see which age groups had higher survival rates.
-  Children had a higher chance of survival.
-  Older passengers were more likely to not survive.
- Age alone wasn’t enough to predict survival.


"""

sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival Rate by Passenger Class")
plt.show()

"""This helps see which age groups had higher survival rates.

**Conclusion:**

From the analysis, we find that:

*   Women survived more than men.
*   Younger passengers had a higher survival rate.
*   First-class passengers had a better chance of survival.
"""